version: '2'
services:
  web:
    build: ./web-server
    image: vismooc-web-server:0.3.0
    ports:
      - "0.0.0.0:9999:9999"
    volumes:
      - ./config:/config
    depends_on:
      - db
      - redis
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "10"
  data:
    build: ./data-server
    image: vismooc-data-server:0.3.5
    volumes:
        - ./data-server/dist:/dist
        - ./config:/config
    depends_on:
        - db
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "10"
  redis:
    image: redis
  db:
    image: mongo:3.4
    volumes:
        - ./database/data:/data
