version: '2'
services:
  front:
    image: hkustvislab/vismooc-front-end:elearning-master
    ports:
      - "0.0.0.0:8080:80"
    depends_on:
      - web
    environment:
      - WEB_SERVER_HOST=web
      - WEB_SERVER_PORT=9999
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "10"
  web:
    image: hkustvislab/vismooc-web-server:elearning-master
    volumes:
      - ./config:/config
    depends_on:
      - db
      - redis
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "10"
  data:
    image: hkustvislab/vismooc-data-server:elearning-master
    volumes:
        - ./config:/config
    depends_on:
        - db
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "10"
  redis:
    image: redis
  db:
    image: mongo:3.4
    volumes:
        - ./database/data:/data
