version: '2'
services:
  front:
    image: hkustvislab/vismooc-front-end:v0.6.0
    ports:
      - "0.0.0.0:8080:80"
    depends_on:
      - web
    environment:
      - WEB_SERVER_HOST=web
      - WEB_SERVER_PORT=9999
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "10"
  web:
    image: vismooc/vismooc-web-server
    volumes:
      - ./config:/config
    depends_on:
      - db
      - redis
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "10"
  data:
    image: vismooc/vismooc-data-server
    volumes:
        - ./config:/config
    depends_on:
        - db
        - moocdb
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "10"

  moocdb:
    image: mysql:latest
    environment:
     - MYSQL_ROOT_PASSWORD= # fill your password here
    volumes:
     - socket:/var/run/mysqld
     - /data/mitx/MITx__6_00_2x_7__1T2017/mysql:/var/lib/mysql # The directory on the left: datadir volume of MySQL service

  redis:
    image: redis

  db:
    image: mongo:3.4
    volumes:
        - ./database/data:/data

volumes:
  socket: