version: '2'
services:
  web:
    image: hkustvislab/vismooc-web-server:elearning-master
    ports:
      - "0.0.0.0:9998:9999"
    volumes:
      - ./config:/config
    depends_on:
      - db
      - redis
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "10"
  data:
    image: hkustvislab/vismooc-data-server:elearning-master
    volumes:
        - ./config:/config
    depends_on:
        - db
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "10"
  redis:
    image: redis
  db:
    image: mongo:3.4
    volumes:
        - ./database/data:/data
